"""Add clearance_type to vehicle

Revision ID: 0be2fd231f87
Revises: 7cdfd87709e9
Create Date: 2026-02-17 04:50:55.512716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be2fd231f87'
down_revision: Union[str, Sequence[str], None] = '7cdfd87709e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('clearance_type', sa.Enum('FULL', 'RELEASE_GATE', name='clearancetype'), server_default='FULL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'clearance_type')
    # ### end Alembic commands ###
