"""Add full clearance cost fields to vehicle

Revision ID: 8afb374ee904
Revises: 0be2fd231f87
Create Date: 2026-02-17 05:46:01.970416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afb374ee904'
down_revision: Union[str, Sequence[str], None] = '0be2fd231f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('cpc', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('valuation', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('customs_duty', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('comet_shipping', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('terminal_charges', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'terminal_charges')
    op.drop_column('vehicles', 'comet_shipping')
    op.drop_column('vehicles', 'customs_duty')
    op.drop_column('vehicles', 'valuation')
    op.drop_column('vehicles', 'cpc')
    # ### end Alembic commands ###
