"""Add Terminal, Carrier, Ship models and update Vehicle relationships

Revision ID: a1a8ca43e537
Revises: 9675e3c11087
Create Date: 2026-03-01 10:11:44.622186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a8ca43e537'
down_revision: Union[str, Sequence[str], None] = '9675e3c11087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminals_id'), 'terminals', ['id'], unique=False)
    op.create_index(op.f('ix_terminals_name'), 'terminals', ['name'], unique=True)
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_id'), 'carriers', ['id'], unique=False)
    op.create_index(op.f('ix_carriers_name'), 'carriers', ['name'], unique=True)
    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_id'), 'ships', ['id'], unique=False)
    op.create_index(op.f('ix_ships_name'), 'ships', ['name'], unique=True)
    
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('terminal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vehicles_terminal_id', 'terminals', ['terminal_id'], ['id']) # Added explicit name
        batch_op.create_foreign_key('fk_vehicles_ship_id', 'ships', ['ship_id'], ['id'])         # Added explicit name
        batch_op.drop_column('ship_name')
        batch_op.drop_column('terminal')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terminal', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ship_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_vehicles_ship_id', type_='foreignkey')       # Use explicit name
        batch_op.drop_constraint('fk_vehicles_terminal_id', type_='foreignkey') # Use explicit name
        batch_op.drop_column('terminal_id')
        batch_op.drop_column('ship_id')
    op.drop_index(op.f('ix_ships_name'), table_name='ships')
    op.drop_index(op.f('ix_ships_id'), table_name='ships')
    op.drop_table('ships')
    op.drop_index(op.f('ix_carriers_name'), table_name='carriers')
    op.drop_index(op.f('ix_carriers_id'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_terminals_name'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_id'), table_name='terminals')
    op.drop_table('terminals')
    # ### end Alembic commands ###
