"""Add Payment AuditLog update Financials unique vehicle_id

Revision ID: a9045a2d95ea
Revises: a6c935badc51
Create Date: 2026-02-02 04:21:33.975622

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9045a2d95ea'
down_revision: Union[str, Sequence[str], None] = 'a6c935badc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(conn, name: str) -> bool:
    return name in inspect(conn).get_table_names()


def _column_exists(conn, table: str, column: str) -> bool:
    return column in [c["name"] for c in inspect(conn).get_columns(table)]


def _index_exists(conn, table: str, index_name: str) -> bool:
    return index_name in [i["name"] for i in inspect(conn).get_indexes(table)]


def upgrade() -> None:
    """Upgrade schema. Idempotent to handle partial runs."""
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists(conn, "audit_logs"):
        op.create_table('audit_logs',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('action', sa.String(), nullable=False),
            sa.Column('table_name', sa.String(), nullable=False),
            sa.Column('record_id', sa.Integer(), nullable=True),
            sa.Column('old_value', sa.String(), nullable=True),
            sa.Column('new_value', sa.String(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    if not _table_exists(conn, "payments"):
        op.create_table('payments',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('financial_id', sa.Integer(), nullable=False),
            sa.Column('amount', sa.Float(), nullable=False),
            sa.Column('payment_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
            sa.Column('reference', sa.String(), nullable=True),
            sa.Column('recorded_by_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
            sa.Column('notes', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['financial_id'], ['financials.id'], ),
            sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_payments_financial_id'), 'payments', ['financial_id'], unique=False)
        op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    if not _column_exists(conn, "financials", "created_at"):
        op.add_column('financials', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    if not _column_exists(conn, "financials", "updated_at"):
        op.add_column('financials', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    if not _index_exists(conn, "financials", "ix_financials_vehicle_id"):
        op.create_index(op.f('ix_financials_vehicle_id'), 'financials', ['vehicle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financials_vehicle_id'), table_name='financials')
    op.drop_column('financials', 'updated_at')
    op.drop_column('financials', 'created_at')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_financial_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
